name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install
    - name: Build Docker image
      run: |
        docker build -t node-js:latest .
        docker tag node-js:latest shishirraj/ec2_node_deployment:latest

  deploy:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push shishirraj/ec2_node_deployment:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Pull Docker image from Docker Hub
      run: docker pull shishirraj/ec2_node_deployment:latest

    - name: Stop and remove existing Docker container (if any)
      run: docker stop nodejs-container || true && docker rm nodejs-container || true

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name nodejs-container shishirraj/ec2_node_deployment:latest
