name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install



    - name: Build Docker image
      run: |
        docker build -t shishiraj/node-js:latest .
        docker tag shishirraj/node-js:latest shishirraj/node-js:latest

  deploy:
    name: Deploy Docker image
    runs-on: [myrunner1]
    needs: build

    steps:
    - name: Fetch Docker Hub credentials
      run: echo "${{ secrets.DOCKERHUB_USERNAME }}\n${{ secrets.DOCKERHUB_PASSWORD }}" > ~/.docker/config.json

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push shishirraj/node-js:latest

    - name: Pull Docker image from Docker Hub
      run: docker pull shishirraj/node-js:latest

    - name: Stop and remove existing Docker container (if any)
      run: docker stop nodejs-container || true && docker rm nodejs-container || true

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name nodejs-container shishirraj/node-js:latest
